define('config', [ 'lodash' ], function(_) {
  /**
   * @class Config
   *
   * Application-wide configuration.
   *
   * This object is exposed to the modules after initialization of the Controller
   * via the application State.
   */
  var productionConfig = {

    version: '1.0.0',
    apiHost: 'https://toggl.com/reports/api/v2',
    apiToken: '',

    /**
     * The set of available locales, automatically generated by the locale
     * generator script module.
     */
    availableLocales: [
      'en'
    ],

    defaultLocale: 'en',

    xhr: {
      timeout: 15000,
    }
  };

  // development config goes here:
  //

  //>>excludeStart("production", pragmas.production);
  _.merge(productionConfig, {
  });
  //>>excludeEnd("production");

  return productionConfig;
});